//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarritoComprasTuCodigo.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class Producto
    {
        public Producto()
        {
            this.ListaVenta = new HashSet<ListaVenta>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Foto { get; set; }
        public Nullable<int> CategoriaId { get; set; }
        public byte[] Image { get; set; }
        public HttpPostedFileBase FileImg { get; set; }
        public bool? Estatus { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<ListaVenta> ListaVenta { get; set; }
    }
}
